name: 🛠️ Request New Feature
description: Let us know what you would like to see added.
labels: ['enhancement']
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature in detail (also include code, mocks, or screenshots if applicable)
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: What type of pull request would this be?
      options:
        - New Feature
        - Improvement/Enchancement
        - Docs
        - Other
  - type: textarea
    id: references
    attributes:
      label: Provide relevant links or additional information
