# DEPRECATED: Updating project to use n8n-node cli tool. Use "npm run release" instead.
name: Publish

on:
  release:
    types: [published]

env:
  NODE_VERSION: 20

jobs:
  prepublish:
    name: 🔎 Prepublish
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Checkout code
        uses: actions/checkout@v4

      - name: 🛠️ Setup node.js
        uses: actions/setup-node@v4

        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 📥️ Install Dependencies
        run: npm ci

      - name: 🚀 Run prepublish
        run: npm run prepublishOnly --if-present

  publish:
    name: 📤️ Publish Package
    runs-on: ubuntu-latest
    needs: prepublish
    steps:
      - name: ✅ Checkout code
        uses: actions/checkout@v4

      - name: 🛠️ Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: 📥️ Install Dependencies
        run: npm ci

      - name: 🚀 Publish Package to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
